### PR TITLE
Feature/covid data

### PR DESCRIPTION
**Pull request by Pgandhi21**
Cleaned up datapage.js to make it easier to read and understand. Data for Covid and map is getting pulled and uploaded onto html without any issues.

### CODE REVIEW

**Comment by bindi-v** [comment]
great job!

**Comment by bindi-v** [comment]
I think I did mistakenly closed. Reopen it.

**Review by bindi-v — APPROVED** [review]
great!

**Review by abrahamin — APPROVED** [review]
Great work!

**Pull request merged**
